### ISSUE TITLE
[BUG] dartls timeout

### ISSUE THREAD

**Issue by bruce3x** [nvim-flutter/flutter-tools.nvim#248] opened 2023-04-21 12:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Occasionally encountering the error `[LSP][dartls] timeout`, LSP is unable to perform code formatting and autocompletion.
<img width="402" alt="image" src="https://user-images.githubusercontent.com/15318754/233637538-5195aa43-5cdb-494f-89d7-32c3b02db68c.png">
<img width="241" alt="image" src="https://user-images.githubusercontent.com/15318754/233637600-5a4ff748-6f08-456b-80a1-ede61b77f99b.png">

### Expected Behavior

Able to properly format code and provide code autocompletion.

### Steps To Reproduce

Using `gd` to navigate through the Flutter framework classes several  times, this situation is encountered.

### Environment

```Markdown
- OS: macOS 13.3
- Flutter version: Flutter 3.7.6
- Is flutter in $PATH: yes
- neovim version: NVIM v0.9.0
```

### Anything else?

I'm using LazyVim + flutter-tools.nvim .

And after I exit nvim, the Dart process is still running.

```
  501 56484     1   0  8:41PM ??         0:21.65 ~/.asdf/installs/flutter/3.7.6-stable/bin/cache/dart-sdk/bin/dart ~/.asdf/installs/flutter/3.7.6-stable/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --lsp
  501 56584 56484   0  8:41PM ??         0:00.71 ~/.asdf/installs/flutter/3.7.6-stable/bin/cache/dart-sdk/bin/dart pub upgrade
```

**Comment by akinsho** [comment] 2023-04-21 15:48
@bruce3x I don't believe this issue is caused by this plugin and is likely coming from neovim's lsp client or from dart ls itself. This plugin doesn't actually control the internal of the language server it starts and most of the moment to moment is essentially between neovim and the dart ls.

**Comment by bruce3x** [comment] 2023-04-21 16:18
First of all, thank you for developing this very useful plugin.

I am using Neovim for development for a short time and am not familiar with it. Could you guide me on how to troubleshoot or analyze this issue?

**Comment by akinsho** [comment] 2023-04-21 16:35
Honestly @bruce3x I don't really know I guess one thing you can do is to check the LSP logs to see if there is any information or errors that might point to what is going on
e.g. `:lua vim.cmd('edit '..vim.lsp.get_log_path())` this will show you the log file. I would look for errors in there that might explain what is happening.

**Comment by brutusmcforce** [comment] 2023-04-23 11:11
I am also having this problem since a couple of weeks back. Neovim freezes entirely due to what I assume are LSP timeouts from dartls. It only happens sometimes but it is reproducable, as in if it happens I can trigger it by trying the same completion that made it freeze the first time.

OS: Arch Linux
Flutter version: 3.7.8
Dart SDK version: 2.19.5 (stable)
Neovim version: VIM v0.9.0 (using LazyVim)

I find nothing in the LSP log. I realize this might be a problem with dartls, but seeing as I don't even know where to begin debugging this I am calling out here where there are people a lot more experienced with these specific tools.

**Comment by rishin27** [comment] 2023-04-23 13:30
I am also facing similar issues, once the lsp server quits even :LspRestart does not help.

To reproduce it

- :FlutterRun
- Once Flutter Run command is complete, a command dialog asks to press any key to continue. 
- Once you confirm, the file you are editing suddenly goes into readonly mode. You can use :w! to recover from that.
- After which you get an error -  "LSP: unable to edit document because not previously opened"? <- this is where lsp quits and fails to recover even with autostart = True.

My guess is though you can recover the buffer you are editing from readonly mode. But the LSP still sees it in readonly mode. Also there is nothing about it in the logs, errors are visible with :messages.

Workaround - reload the file with :e!  -> https://vi.stackexchange.com/questions/41588/to-whom-do-i-report-error-lsp-unable-to-edit-document-because-not-previously-o

Hope this helps.

and @akinsho  great work on the plugin :clap:

**Comment by akinsho** [comment] 2023-04-23 13:42
> Once you confirm, the file you are editing suddenly goes into readonly mode. You can use :w! to recover from that.
After which you get an error - "LSP: unable to edit document because not previously opened"? <- this is where lsp quits and fails to recover even with autostart = True.

I think this report might be beginning to mix too many things since the OP post refers directly to and includes a screenshot of a timeout. The second post refers to a freeze but it's not actually clear if it's from a timeout and @rishin27 your post is more talking about the fact that this plugin actually deliberately makes your dependency files readonly since presumably you do not intend to edit the code of a dependency file. This was actually copied from the dart-vim plugin which was actually written by a member of the dart team. I don't know if that now causes some issue with neovim but since I encounter readonly files in other environments and neovim behaves properly that doesn't sound likely.


In either case thanks for the reports but at the moment I don't really have any single clear mechanism for how to reproduce the *main thing that this issue is for* I don't really think I understand specifically what I should be thinking about fixing and more importantly if it really truly relates to this plugin or not.

What versions of flutter are people using? what actually is the specific problem statement if it's not the same as the OP I think it's best to not include it etc.

Re. reproduction I need minimal lua init files please, not dotfiles please, going through people's dotfiles to reproduce bugs is a huge pain.

**Comment by bruce3x** [comment] 2023-04-26 03:32
@brutusmcforce  
For the issue of neovim freeze, I searched a lot and finally found a solution in the [LazyVim discussions](https://github.com/LazyVim/LazyVim/discussions/43#discussioncomment-4656727).

After disabling `noice` plugin, I haven't encountered the freezing issues recently.

`{"folke/noice.nvim", enabled = false}`

**Comment by NiamhFerns** [comment] 2023-09-13 20:40
If [@bruce3x's fix](https://github.com/akinsho/flutter-tools.nvim/issues/248#issuecomment-1522725543) doesn't work for anyone reading this, I've found that [indent-blankline.nvim](https://github.com/lukas-reineke/indent-blankline.nvim) can cause freezing as well. Try excluding dart files in your `filetype_exclude` opt.

**Comment by geardy47** [comment] 2023-11-22 14:42
@bruce3x I'm facing the same problem with you (dartls timeout), try to uninstall dart in treesitter using `TSUninstall dart`. I haven't encountered the timeout again.

**Comment by Hecatoncheir** [comment] 2024-01-15 09:34
> @bruce3x I'm facing the same problem with you (dartls timeout), try to uninstall dart in treesitter using `TSUninstall dart`. I haven't encountered the timeout again.

Without treesitter dart neotest does not work.
![Screenshot 2024-01-15 at 12 29 53](https://github.com/akinsho/flutter-tools.nvim/assets/910917/e27920b6-da02-4ffe-8ce7-f946eabda8f4)

**Comment by sidlatau** [comment] 2024-01-15 09:50
> > @bruce3x I'm facing the same problem with you (dartls timeout), try to uninstall dart in treesitter using `TSUninstall dart`. I haven't encountered the timeout again.
> 
> Without treesitter dart neotest does not work. ![Screenshot 2024-01-15 at 12 29 53](https://private-user-images.githubusercontent.com/910917/296712948-e27920b6-da02-4ffe-8ce7-f946eabda8f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMTIzNzksIm5iZiI6MTcwNTMxMjA3OSwicGF0aCI6Ii85MTA5MTcvMjk2NzEyOTQ4LWUyNzkyMGI2LWRhMDItNGZmZS04Y2U3LWY5NDZlYWJkYThmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQwOTQ3NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZGFkMGE3MmRiMjMwZDg5YTQ5YmI0OWEyNjcwNDA2YTM4MDZiYzE1ZjlmZGNiNzdhZGE1ZDMzZDg1MGIxZmQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iYfTkUKeYEgSL-xIHM3tCJE-DZC71JWQDGD6AuxI9-A)

You may add this in the test adapter config, and then LSP information will be used instead of Treesitter to get test names:
```lua
use_lsp = true,
```

**Comment by Hecatoncheir** [comment] 2024-01-15 10:12
> > > @bruce3x I'm facing the same problem with you (dartls timeout), try to uninstall dart in treesitter using `TSUninstall dart`. I haven't encountered the timeout again.
> > 
> > 
> > Without treesitter dart neotest does not work. ![Screenshot 2024-01-15 at 12 29 53](https://private-user-images.githubusercontent.com/910917/296712948-e27920b6-da02-4ffe-8ce7-f946eabda8f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMTIzNzksIm5iZiI6MTcwNTMxMjA3OSwicGF0aCI6Ii85MTA5MTcvMjk2NzEyOTQ4LWUyNzkyMGI2LWRhMDItNGZmZS04Y2U3LWY5NDZlYWJkYThmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQwOTQ3NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZGFkMGE3MmRiMjMwZDg5YTQ5YmI0OWEyNjcwNDA2YTM4MDZiYzE1ZjlmZGNiNzdhZGE1ZDMzZDg1MGIxZmQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iYfTkUKeYEgSL-xIHM3tCJE-DZC71JWQDGD6AuxI9-A)
> 
> You may add this in the test adapter config, and then LSP information will be used instead of Treesitter to get test names:
> 
> ```lua
> use_lsp = true,
> ```



But after parsing, the tests do not run.
https://github.com/Hecatoncheir/neovim/blob/main/lua/plugins/neotest.lua#L14

![Screenshot 2024-01-15 at 13 08 37](https://github.com/akinsho/flutter-tools.nvim/assets/910917/43c63aaa-5664-45c9-8c1e-8d474bf9a814)
![Screenshot 2024-01-15 at 13 09 15](https://github.com/akinsho/flutter-tools.nvim/assets/910917/b8f5cc1e-ff26-4557-9b4f-b0653f19bc61)
![Screenshot 2024-01-15 at 13 09 06](https://github.com/akinsho/flutter-tools.nvim/assets/910917/5f022b28-4499-4ddc-9df4-5237195f9500)

**Comment by sidlatau** [comment] 2024-01-15 10:41
Hmm, @Hecatoncheir, could you register a bug with repro steps in https://github.com/sidlatau/neotest-dart/issues?

**Comment by Hecatoncheir** [comment] 2024-01-15 13:24
All work perfect with that configuration: https://github.com/Hecatoncheir/neovim/blob/main/lua/plugins/neotest.lua

**Comment by geardy47** [comment] 2024-02-28 08:53
> All work perfect with that configuration: https://github.com/Hecatoncheir/neovim/blob/main/lua/plugins/neotest.lua

I've copy your config yet still got `No test found`, do you know why?

**Comment by Hecatoncheir** [comment] 2024-02-28 11:07
It's look like this for now:  https://github.com/Hecatoncheir/neovim/blob/a8cb48858c426a1c647a5c81c389d014b703bf2b/lua/plugins/languages/dart.lua#L65
Neotest add here: https://github.com/Hecatoncheir/neovim/blob/a8cb48858c426a1c647a5c81c389d014b703bf2b/lua/core/plugins.lua#L39 and setup: https://github.com/Hecatoncheir/neovim/blob/a8cb48858c426a1c647a5c81c389d014b703bf2b/lua/plugins/ui/tests.lua#L2

**Comment by sidlatau** [comment] 2024-09-08 20:36
Closing this, as it looks like other plugins are causing an issue, and there is no clear action on how to move forward.

**Closed by sidlatau** 2024-09-08 20:36 UTC
