### ISSUE TITLE
[Bug]: Closing tags does not appear

### ISSUE THREAD

**Issue by umtdemr** [nvim-flutter/flutter-tools.nvim#101] opened 2021-10-21 11:04 UTC
**Describe the bug**
Closing tags does not appear when i open a flutter project. Changing default settings did not work.

```lua
require("flutter-tools").setup{
   closing_tags = {
    highlight = "ErrorMsg", -- highlight for the closing tag
    prefix = ">", -- character to use for close tag e.g. > Widget
    enabled = true -- set to false to disable
  }
}
```

or i tried like this too:

```lua
require("flutter-tools").setup{}
```

**To Reproduce**

1. Open project with vim

**Expected behavior**
Closing tags should appear when we open flutter project.

**Screenshots**

![flutter_tools_bug_report](https://user-images.githubusercontent.com/61540809/138263316-a4fa3ca4-339b-4f23-8fb5-729df36e174e.png)

**System information**

- OS: Arch Linux (Manjaro 21.1.5)
- Flutter version: 2.2.1 stable
- Is flutter in $PATH: yes
- neovim version: v0.6.0-dev+478-ge7ea54a3d

**Comment by umtdemr** [comment] 2021-10-21 14:45
Hi @akinsho,

Here is a screenshot of `:LspInfo`
![2021-10-21_17-41](https://user-images.githubusercontent.com/61540809/138301543-e777ca34-d756-47a5-a1df-6403af3989e3.png)

dartls is working. I tested it with code actions, hover doc... etc

**Comment by akinsho** [comment] 2021-11-18 09:34
Any news here? I still can't reproduce this issue. Can you post some information about what OS you are using and what version of neovim you are running etc.

**Comment by umtdemr** [comment] 2021-11-21 19:03
Hello, since I moved to collage dorm, the internet slowed down.  Beacuse of it I can't try it right now. I will try again it when i go to home again.

**Comment by akinsho** [comment] 2022-07-14 10:03
I'm going to close this out as I was never able to reproduce it and no one else ever reported this issue, so I believe it is a problem with the OP's config

**Closed as completed by akinsho** 2022-07-14 10:03 UTC
