### ISSUE TITLE
[BUG] multiline strings break neovim

### ISSUE THREAD

**Issue by flexagoon** [nvim-flutter/flutter-tools.nvim#398] opened 2024-10-18 23:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you use a multiline string in your code, entering insert mode in that file will show the following error:

![Uploading image.png…]()

### Expected Behavior

It shouldn't break

### Steps To Reproduce

Pass a multiline string to a flutter widget:
![image](https://github.com/user-attachments/assets/28cd3e67-4a26-4029-b4fe-7bebd9a6b1d4)

### Environment

```Markdown
- OS: Fedora Silverblue 40
- Flutter version: 3.24.3
- Is flutter in $PATH: Yes
- neovim version: v0.11.0-dev+982-gf72dc2b4c
```

**Comment by sidlatau** [comment] 2024-10-21 17:22
@flexagoon, I see the error screenshot is not loaded, no error is visible. Can you reupload the screenshot?

**Comment by flexagoon** [comment] 2024-10-21 19:01
@sidlatau sorry, here's the error:

![image](https://github.com/user-attachments/assets/c1450437-3685-452f-a1e0-12f93b8a9613)

**Comment by sidlatau** [comment] 2024-10-21 19:45
This is a duplicate of https://github.com/nvim-flutter/flutter-tools.nvim/issues/395
The workaround is to downgrade nvim to 0.10.1 as the linked issue suggests.

**Closed by sidlatau** 2024-10-21 19:45 UTC
